const copy: Record<string, string> = {
  "Pertahankan konsistensi belajar harian dan buat jadwal teratur untuk menyeimbangkan istirahat dan tugas.": "Pilih jadwal belajar yang bisa kamu jalani. Sisakan ruang untuk tugas dan istirahat.",
  "Performa akademik sangat kuat. Pertahankan metode belajar aktif dan eksplorasi materi lanjutan secara mandiri.": "Pertahankan kebiasaan yang sudah berjalan. Coba mengingat kembali materi dengan kata-katamu sendiri.",
  "Fokuskan waktu pada mata kuliah berbobot tinggi, kurangi distraksi layar, dan manfaatkan teknik Pomodoro untuk menjaga konsistensi.": "Mulai dari satu tugas penting. Kurangi gangguan selama belajar dan coba sesi fokus singkat.",
  Low: "Perlu perhatian", Average: "Mulai terbentuk", Good: "Cukup terjaga", Excellent: "Terjaga baik",
  "Moderate Performance": "Mulai terbentuk", "High Academic Performance": "Terjaga baik", "Needs Academic Support": "Perlu perhatian",
  "You need to improve study consistency and attendance.": "Mulai dari jadwal belajar yang bisa kamu jalani dan perbaiki kehadiran secara bertahap.",
  "Your performance is stable but can be improved with better study habits.": "Kebiasaan belajarmu mulai terbentuk. Pilih satu hal yang ingin kamu perbaiki minggu ini.",
  "You are performing well. Maintain your current learning habits.": "Pertahankan kebiasaan yang sudah berjalan dan sisakan waktu untuk istirahat.",
  "Excellent performance. Continue your current study routine.": "Rutinitasmu sudah mendukung belajar. Jaga ritmenya dan sesuaikan saat beban tugas berubah.",
  "Strong study dedication": "Waktu belajar cukup terjaga",
  "Low study hours — aim for at least 3-4 hours daily": "Waktu belajar masih perlu diperhatikan",
  "Excellent class attendance": "Kehadiran kuliah terjaga",
  "Low attendance — try to attend at least 85% of classes": "Kehadiran kuliah masih perlu diperhatikan",
  "Healthy sleep schedule": "Waktu tidur cukup",
  "Insufficient sleep — aim for 7-8 hours per night": "Waktu tidur masih kurang",
  "Good mental wellbeing": "Kondisi diri terasa baik",
  "Mental health needs attention — consider counseling resources": "Kondisi diri perlu perhatian. Pertimbangkan mencari dukungan jika diperlukan",
  "Active physical lifestyle": "Ada waktu untuk bergerak",
  "No exercise — even 2-3 sessions per week can boost focus": "Belum ada waktu olahraga dalam jawabanmu",
  "Controlled screen time": "Waktu media sosial cukup terkendali",
  "High social media usage — try limiting to 2 hours daily": "Waktu media sosial cukup tinggi",
  "Good dietary habits": "Pola makan terjaga",
  "Poor diet quality — balanced nutrition improves concentration": "Pola makan perlu diperhatikan",
  "Active in extracurricular activities": "Aktif berkegiatan di luar kelas",
  "Good internet connectivity for learning": "Koneksi internet mendukung belajar",
  "Poor internet — consider campus/library resources": "Koneksi internet bisa menghambat belajar",
  "Willingness to improve through self-assessment": "Sudah meluangkan waktu untuk mengenali kebiasaanmu",
  "Maintain your current habits to stay on track": "Belum ada catatan tambahan dari perhitungan ini",
  "Durasi belajar harian yang sangat baik": "Waktu belajar cukup terjaga",
  "Durasi belajar mandiri masih perlu ditingkatkan": "Waktu belajar mandiri perlu diperhatikan",
  "Tingkat kehadiran kuliah tinggi dan konsisten": "Kehadiran kuliah terjaga",
  "Kehadiran perkuliahan perlu ditingkatkan": "Kehadiran kuliah perlu diperhatikan",
  "Waktu layar hiburan & media sosial relatif tinggi": "Waktu hiburan dan media sosial cukup tinggi",
  "Pengendalian waktu layar hiburan terkontrol dengan baik": "Waktu hiburan cukup terkendali",
  "Pola tidur cukup mendukung pemulihan kognitif": "Waktu tidur cukup",
  "Kurang tidur dapat menurunkan konsentrasi belajar": "Waktu tidur masih kurang",
};

export function insightCopy(text: string) { return copy[text] || text; }
